NGK_G11_Aflv3/NGK_G11_Aflv3/Controllers/ObservationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NGK_G11_Aflv3.Infrastructure;
using NGK_G11_Aflv3.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NGK_G11_Aflv3.Controllers
{
	public class ObservationsController : Controller
	{
		private readonly VejrAppContext context;
        private readonly IWebHostEnvironment webHostEnviroment;

		public ObservationsController(VejrAppContext context, IWebHostEnvironment webHostEnviroment)
		{
			this.context = context;
            this.webHostEnviroment = webHostEnviroment;
		}

		//GET/Observations
		public async Task<IActionResult> Index()
		{
			return View(await context.Observations.OrderByDescending(x => x.ObservationsId).Include(x => x.Location).ToListAsync());
		}

        //Get/Observations/create
        [Authorize]
        public IActionResult Create()
		{
			ViewBag.LocationsId = new SelectList(context.Locations.OrderBy(x => x.Sorting), "ObservationsId", "Name");
			return View();
		}

        //Post/Observations/Create
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Observations Observations)
        {
            ViewBag.LocationId = new SelectList(context.Locations.OrderBy(x => x.Sorting), "Id", "Name");

            if (ModelState.IsValid)
            {
                Observations.Slug = Observations.Name.ToLower().Replace(" ", "-");
              
                var slug = await context.Observations.FirstOrDefaultAsync(x => x.Slug == Observations.Slug);
                if (slug != null)
                {
                    ModelState.AddModelError("", "The Observation already exists. ");
                    return View(Observations);
                }

                context.Add(Observations);
                await context.SaveChangesAsync();

                TempData["Success"] = "The Observation has been added";

                return RedirectToAction("Index");
            }

            return View(Observations);
        }

        // GET/ Observation/details/5
        public async Task<IActionResult> Details(int id)
        {
            Observations Observations = await context.Observations.Include(x => x.Location).FirstOrDefaultAsync(x => x.ObservationsId == id);
            if (Observations == null)
            {
                return NotFound();
            }

            return View(Observations);
        }

        //GET/ Observations/GetLatestTemp/5
        [HttpGet]
        public List<Observations> GetLatestTemp()
        {           
            var LatestData = context.Observations.Take(3).ToList();
            return LatestData;            
        }

        [HttpGet]
        public List<Observations> GetByDate(DateTime date)
        {
			var byDate = context.Observations.Where(x => x.Time.Date == date.Date).ToList();

            return byDate;
        }

        //Get/Observations/GetByInterval/5
        [HttpGet]
        public List<Observations> GetByInterval(DateTime dateStart, DateTime dateend)
        {
			if (dateStart < dateend)
			{
                var byDate = context.Observations.Where(x => x.Time.Date >= dateStart.Date && x.Time.Date <= dateend.Date).ToList();

                return byDate;
            }

            return null; 
        }

        //Get/Observations/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            Observations Observations = await context.Observations.FindAsync(id);
            if (Observations == null)
            {
                TempData["Error"] = "The Observation does not exist!";
            }
            else
            {
                context.Observations.Remove(Observations);
                await context.SaveChangesAsync();
                TempData["Success"] = "The Observation has been deleted";
            }

            return RedirectToAction("Index");
        }
    }
}

NGK_G11_Aflv3/NGK_G11_Aflv3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NGK_G11_Aflv3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
	<header>
		<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
			<div class="container">
				<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NGK_G11_Aflv3</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
						aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
					<ul class="navbar-nav flex-grow-1 justify-content-end">

						

						@if (User?.Identity?.IsAuthenticated ?? false)
						{
							<li class="nav-item">
								<a asp-controller="Account" asp-action="Logout" class="btn btn-danger">Hi, @User.Identity.Name, Log out</a>
							</li>
						}
						else
						{
							<li class="nav-item">
								<a asp-controller="Account" asp-action="Login" class="btn btn-success">Log in</a>
							</li>
							<li class="nav-item ml-1">
								<a asp-controller="Account" asp-action="Register" class="btn btn-primary">Register</a>
							</li>
						}

					</ul>
					<ul class="navbar-nav flex-grow-1">
						<a class="nav-link text-dark" asp-controller="Observations" asp-action="Index">Observationer</a>
					</ul>
				</div>
			</div>
		</nav>
	</header>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/lib/ckeditor/ckeditor.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>